### ISSUE TITLE
Links to site

### ISSUE THREAD

**Issue by WorkInProgress-Development** [ryanmonro/george#3]
Link on the about section of the repository goes to ryanmonro.com/george/, which redirects to http://1194online.com.
Should the link be changed to 1194online.com, and the redirect on your site to use https? Just a suggestion

**Comment by ryanmonro** [comment]
Agreed! Thanks for noticing. I guess I never changed the URL in the about section since I bought the domain.
I had trouble allowing 1194online.com and www.1194online.com without https complicating things. I never really solved that.
